import type { Profile } from '../types.js';
import { escapeXml } from '../utils/svg.js';

export function readme(profile: Profile): string {
  const projectLinks = profile.projects.filter((p) => p.repository).map((p) => `- [${p.name}](${p.repository})`).join('\n');
  const contacts = profile.contact.map((item) => `[${item.label}](${item.url})`).join(' · ');
  const profileLink = profile.github.username ? `Explore the code and experiments across [my repositories](https://github.com/${profile.github.username}?tab=repositories).` : 'Repository links and contact details can be enabled in `data/profile.json` when ready.';
  return `<!-- Generated by npm run build. Edit data/profile.json or the generators, not this file. -->
<div align="center">

![${escapeXml(profile.avatar.alt)} and ${escapeXml(profile.displayName)} profile banner](assets/hero.svg)

</div>

## Profile

![Professional profile summary](assets/profile.svg)

## Talents

![Technical skills grouped by discipline](assets/talents.svg)

## Party Setup

![Engineering stack represented as a compact party setup](assets/party-setup.svg)

## Featured Projects

![Three featured AI engineering projects](assets/projects.svg)
${projectLinks ? `\n${projectLinks}\n` : ''}
## GitHub Activity

![GitHub activity panel](assets/achievements.svg)

${profileLink}

<div align="center">

<sub>Designing, building, and deploying practical intelligent systems.</sub>

<br />

<sub>Dream-themed portrait generated with OpenAI image generation tools; this repository does not include official HoYoverse artwork. See <a href="assets/ASSET_SOURCES.md">asset notes</a>.</sub>
${contacts ? `\n<br />\n\n<sub>${contacts}</sub>` : ''}

</div>
`;
}
