import type { Profile } from '../types.js';
import { escapeXml } from '../utils/svg.js';

export function readme(profile: Profile): string {
  const contacts = profile.contact.map((item) => `[${item.label}](${item.url})`).join(' · ');
  const stack = profile.skills.map((group) => `- **${group.group}** — ${group.items.map((item) => `\`${item}\``).join(' · ')}`).join('\n');
  const projects = profile.projects.map((project) => {
    const name = project.repository ? `[${project.name}](${project.repository})` : project.name;
    return `- **${name}** — ${project.description}\n  \n  ${project.technologies.map((item) => `\`${item}\``).join(' · ')}`;
  }).join('\n\n');
  const profileLink = profile.github.username
    ? `Explore ongoing experiments and public work in [my repositories](https://github.com/${profile.github.username}?tab=repositories).`
    : 'Public repositories, experiments, and contribution history are available directly from this GitHub profile.';
  return `<!-- Generated by npm run build. Edit data/profile.json or the generators, not this file. -->
<div align="center">

![${escapeXml(profile.avatar.alt)} and ${escapeXml(profile.displayName)} profile banner](assets/hero.svg)

</div>

## About

${profile.summary}

My current interests include ${profile.keywords.join(', ')}, retrieval-augmented systems, and reliable backend infrastructure for AI applications.

## Core Stack

${stack}

## Featured Projects

${projects}

## GitHub Activity

${profileLink}

---

<div align="center">

<sub>Designing, building, and deploying practical intelligent systems.<br />Dream-themed portrait generated with OpenAI image generation tools; no official HoYoverse artwork is included. <a href="assets/ASSET_SOURCES.md">Asset notes</a>.</sub>
${contacts ? `\n<br />\n\n<sub>${contacts}</sub>` : ''}

</div>
`;
}
