import type { Profile } from '../types.js';
import { escapeXml } from '../utils/svg.js';

export function readme(profile: Profile): string {
  const contacts = profile.contact.map((item) => `[${item.label}](${item.url})`).join(' · ');
  const stack = profile.skills.map((group) => `**${group.group}:** ${group.items.map((item) => `\`${item}\``).join(' · ')}`).join('  \n');
  const projects = profile.projects.map((project) => {
    const name = project.repository ? `[${project.name}](${project.repository})` : project.name;
    return `- **${name}** — ${project.description}  \n  ${project.technologies.map((item) => `\`${item}\``).join(' · ')}`;
  }).join('\n\n');
  const party = profile.party.map((item) => `**${item.slot}:** ${item.technology}`).join(' · ');
  const profileLink = profile.github.username
    ? `Explore ongoing experiments and public work in [my repositories](https://github.com/${profile.github.username}?tab=repositories).`
    : 'Public repositories, experiments, and contribution history are available directly from this GitHub profile.';
  return `<!-- Generated by npm run build. Edit data/profile.json or the generators, not this file. -->
<div align="center">

<picture>
  <source media="(prefers-reduced-motion: reduce)" srcset="assets/hero-static.svg">
  <img src="assets/hero.svg" width="100%" alt="${escapeXml(profile.avatar.alt)} and ${escapeXml(profile.displayName)} profile banner" />
</picture>

</div>

![About Gia Phat — character profile panel](assets/about.svg)

${profile.summary}

![Talents — core technical stack](assets/talents.svg)

${stack}

![Party Setup — practical engineering composition](assets/party-setup.svg)

${party}

![Featured AI engineering projects](assets/projects.svg)

${projects}

![GitHub activity](assets/activity.svg)

${profileLink}

---

<div align="center">

<sub>Designing, building, and deploying practical intelligent systems.<br />Dream-themed portrait generated with OpenAI image generation tools; no official HoYoverse artwork is included. <a href="assets/ASSET_SOURCES.md">Asset notes</a>.</sub>
${contacts ? `\n<br />\n\n<sub>${contacts}</sub>` : ''}

</div>
`;
}
